from _typeshed import SupportsWrite
from typing import Final

LICENSE: Final[list[str]]
MAINPAGE: Final[str]

def comment(code: str) -> str: ...
def block_comment(code: str) -> str: ...
def translateFunctionName(name: str) -> str: ...
def translateTypeName(name: str, mangle: bool = True) -> str: ...
def translated_type_name(type: int, scoped: bool = True) -> str: ...
def processElement(handle: SupportsWrite[str], element: int) -> None: ...
def processFunction(handle: SupportsWrite[str], function: int, isConstructor: bool = False) -> None: ...
def processType(handle: SupportsWrite[str], type: int) -> None: ...
def processModule(handle: SupportsWrite[str], package: str) -> None: ...
