__all__: list[str] = []

def GetBool(sym: str, default: bool = ...) -> bool: ...
def GetInt(sym: str, default: int = ...) -> int: ...
def GetDouble(sym: str, default: float = ...) -> float: ...
def GetString(sym: str, default: str = ...) -> str: ...
GetFloat = GetDouble
