__all__ = ['EventGroup']

from collections.abc import Iterable

from .DirectObject import DirectObject

class EventGroup(DirectObject):
    def __init__(self, name: str, subEvents: Iterable[str] | None = ..., doneEvent: str | None = ...) -> None: ...
    def destroy(self) -> None: ...
    def getName(self) -> str: ...
    def getDoneEvent(self) -> str: ...
    def isCompleted(self) -> bool: ...
    def addEvent(self, eventName: str) -> str: ...
    def newEvent(self, name: str) -> str: ...
