__all__ = [
    'copyFuncs',
    'findClass',
    'rebindClass',
    'replaceAIRFunc',
    'replaceCRFunc',
    'replaceIvalFunc',
    'replaceMessengerFunc',
    'replaceStateFunc',
    'replaceTaskMgrFunc',
]

from _typeshed import StrOrBytesPath
from collections.abc import Callable, Iterable
from typing import Any

def findClass(className: str) -> Any | None: ...
def rebindClass(filename: StrOrBytesPath) -> None: ...
def copyFuncs(fromClass: type, toClass: type) -> None: ...
def replaceMessengerFunc(replaceFuncList: Iterable[tuple[Callable, str, Callable]]) -> None: ...
def replaceTaskMgrFunc(replaceFuncList: Iterable[tuple[Callable, str, Callable]]) -> None: ...
def replaceStateFunc(replaceFuncList: Iterable[tuple[Callable, str, Callable]]) -> None: ...
def replaceCRFunc(replaceFuncList: Iterable[tuple[Callable, str, Callable]]) -> None: ...
def replaceAIRFunc(replaceFuncList: Iterable[tuple[Callable, str, Callable]]) -> None: ...
def replaceIvalFunc(replaceFuncList: Iterable[tuple[Callable, str, Callable]]) -> None: ...
