from abc import ABC, abstractmethod
from collections.abc import Generator
from typing import Any, ClassVar

from .DirectObject import DirectObject
from .PythonUtil import ScratchPad

class Job(DirectObject, ABC):
    Done: ClassVar[object]
    Continue: ClassVar[None]
    Sleep: ClassVar[object]
    Priorities: ClassVar[ScratchPad[int]]
    def __init__(self, name: str) -> None: ...
    def destroy(self) -> None: ...
    def getFinishedEvent(self) -> str: ...
    @abstractmethod
    def run(self) -> Generator[Any | None, None, None]: ...
    def getPriority(self) -> int: ...
    def setPriority(self) -> int: ...
    def printingBegin(self) -> None: ...
    def printingEnd(self) -> None: ...
    def resume(self) -> None: ...
    def suspend(self) -> None: ...
    def isFinished(self) -> bool: ...
    def finished(self) -> None: ...
    def getJobName(self) -> str: ...
