class LeakDetector:
    def __init__(self) -> None: ...
    def destroy(self) -> None: ...
    def getLeakDetectorKey(self) -> str: ...

class ObjectTypeLeakDetector(LeakDetector):
    def __init__(self, otld: ObjectTypesLeakDetector, objType, generation) -> None: ...
    def __len__(self) -> int: ...

class ObjectTypesLeakDetector(LeakDetector):
    def __len__(self) -> int: ...

class GarbageLeakDetector(LeakDetector):
    def __len__(self) -> int: ...

class SceneGraphLeakDetector(LeakDetector):
    def __init__(self, render) -> None: ...
    def __len__(self) -> int: ...

class CppMemoryUsage(LeakDetector):
    def __len__(self) -> int: ...

class TaskLeakDetectorBase: ...

class TaskLeakDetector(LeakDetector, TaskLeakDetectorBase):
    def __len__(self) -> int: ...

class MessageLeakDetectorBase: ...

class MessageTypesLeakDetector(LeakDetector, MessageLeakDetectorBase):
    def __len__(self) -> int: ...

class MessageListenerTypesLeakDetector(LeakDetector):
    def __len__(self) -> int: ...
