from collections.abc import Generator, Reversible, Sized
from typing import Any

from .Job import Job

class ReferrerSearch(Job):
    obj: object
    maxRefs: int
    visited: set
    depth: int
    found: int
    shouldPrintStats: bool
    def __init__(self, obj: object, maxRefs: int = 100) -> None: ...
    def __call__(self) -> None: ...
    def run(self) -> Generator[Any | None, None, None]: ...
    def finished(self) -> None: ...
    def __del__(self) -> None: ...
    def truncateAtNewLine(self, s: str) -> str: ...
    def printStatsWhenAble(self) -> None: ...
    def myrepr(self, referrer: object, refersTo: object) -> str: ...
    def step(self, depth: int, path: Reversible) -> None: ...
    def stepGenerator(self, depth: int, path: Reversible): ...
    def printStats(self, path: Reversible) -> None: ...
    def isAtRoot(self, at: object, path: Reversible) -> bool: ...
    def isManyRef(self, at: object, path: Reversible, referrers: Sized) -> bool | None: ...
