__all__ = ['register']

from _typeshed import StrOrBytesPath
from importlib.abc import Loader, SourceLoader
from importlib.machinery import ModuleSpec
from types import CodeType, ModuleType
from typing import Any, Final, Literal

from panda3d.core import Filename, VirtualFile, VirtualFileSystem

vfs: Final[VirtualFileSystem]

class VFSFinder:
    def __init__(self, path: str) -> None: ...
    def find_spec(self, fullname: str, target: ModuleType | None = None) -> ModuleSpec | None: ...

class VFSLoader(Loader):
    dir_path: StrOrBytesPath
    timestamp: int | None
    filename: Filename
    desc: tuple[str, str, int]
    packagePath: Filename | None
    def __init__(self, fullname: str, vfile: VirtualFile) -> None: ...
    def is_package(self, fullname): ...
    def create_module(self, spec: ModuleSpec) -> ModuleType | None: ...
    def exec_module(self, module: ModuleType) -> None: ...
    def get_filename(self, fullname: str) -> str: ...
    @staticmethod
    def get_data(path: str) -> bytes: ...
    @staticmethod
    def path_stats(path: str) -> dict[str, Any]: ...
    @staticmethod
    def path_mtime(path: str) -> int: ...

class VFSSourceLoader(VFSLoader, SourceLoader):  # type: ignore[misc]
    def get_source(self, fullname: str) -> str: ...

class VFSCompiledLoader(VFSLoader):
    def get_code(self, fullname: str) -> CodeType | None: ...
    def get_source(self, fullname: str) -> None: ...

class VFSExtensionLoader(VFSLoader):
    def create_module(self, spec: ModuleSpec) -> ModuleType: ...
    def exec_module(self, module: ModuleType) -> None: ...
    def is_package(self, fullname: str) -> Literal[False]: ...
    def get_code(self, fullname: str) -> None: ...
    def get_source(self, fullname: str) -> None: ...

class VFSNamespaceLoader(Loader):
    def create_module(self, spec: ModuleSpec) -> ModuleType | None: ...
    def exec_module(self, module: ModuleType) -> None: ...
    def is_package(self, fullname: str) -> Literal[False]: ...
    def get_source(self, fullname: str) -> str: ...
    def get_code(self, fullname: str) -> CodeType: ...

def register() -> None: ...
