from typing_extensions import Final, Literal

UID: Final[Literal[0]]
PROP_NAME: Final[Literal[1]]
FRAME: Final[Literal[0]]
VALUE: Final[Literal[1]]
INSLOPE: Final[Literal[2]]
OUTSLOPE: Final[Literal[3]]
NODE: Final[Literal[0]]
CURVE: Final[Literal[1]]
TIME: Final[Literal[2]]
KEY: Final[Literal[0]]
I: Final[Literal[1]]
KEYFRAME: Final[Literal[2]]
IN_TANGENT: Final[Literal[3]]
OUT_TANGENT: Final[Literal[4]]
IN_SLOPE: Final[Literal[5]]
OUT_SLOPE: Final[Literal[6]]
LOCAL_VALUE: Final[Literal[0]]
SELECT: Final[Literal[1]]
X: Final[Literal[0]]
Y: Final[Literal[1]]
Z: Final[Literal[2]]
