from typing import Final

UID: Final = 0
PROP_NAME: Final = 1
FRAME: Final = 0
VALUE: Final = 1
INSLOPE: Final = 2
OUTSLOPE: Final = 3
NODE: Final = 0
CURVE: Final = 1
TIME: Final = 2
KEY: Final = 0
I: Final = 1
KEYFRAME: Final = 2
IN_TANGENT: Final = 3
OUT_TANGENT: Final = 4
IN_SLOPE: Final = 5
OUT_SLOPE: Final = 6
LOCAL_VALUE: Final = 0
SELECT: Final = 1
X: Final = 0
Y: Final = 1
Z: Final = 2
