import wx  # type: ignore[import]
from .LevelEditor import LevelEditor

class CurveAnimUI(wx.Dialog):
    editor: LevelEditor
    nodePath = ...
    curve = ...
    mainPanel: wx.Panel
    chooseNode: wx.StaticText
    chooseNodeTxt: wx.TextCtrl
    chooseNodeButton: wx.Button
    chooseCurve: wx.StaticText
    chooseCurveTxt: wx.TextCtrl
    chooseCurveButton: wx.Button
    duritionTime: wx.StaticText
    duritionTimeSpin: wx.SpinCtrl
    createAnimButton: wx.Button
    saveAnimButton: wx.Button
    time = ...
    curveSequence = ...
    def __init__(self, parent, editor: LevelEditor) -> None: ...
    def SetProperties(self) -> None: ...
    def DoLayout(self) -> None: ...
    def OnChooseNode(self, evt) -> None: ...
    def OnChooseCurve(self, evt) -> None: ...
    def OnCreateAnim(self, evt) -> None: ...
    def OnSaveAnim(self, evt) -> None: ...
    def OnExit(self, evt) -> None: ...
