from os import PathLike

class FileMgr:
    editor = ...
    def __init__(self, editor=None) -> None: ...
    def saveToFile(self, fileName: str | bytes | PathLike | int) -> None: ...
    def loadFromFile(self, fileName: str | bytes) -> None: ...
