from _typeshed import StrOrBytesPath

from .LevelEditor import LevelEditor

class FileMgr:
    editor: LevelEditor
    def __init__(self, editor: LevelEditor | None = ...) -> None: ...
    def saveToFile(self, fileName: StrOrBytesPath | int) -> None: ...
    def loadFromFile(self, fileName: str | bytes) -> None: ...
