from _typeshed import StrOrBytesPath

class FileMgr:
    editor = ...
    def __init__(self, editor=...) -> None: ...
    def saveToFile(self, fileName: StrOrBytesPath | int) -> None: ...
    def loadFromFile(self, fileName: str | bytes) -> None: ...
