import wx  # type: ignore[import]
from wx.lib.scrolledpanel import ScrolledPanel  # type: ignore[import]

class EditHotKeyDialog(wx.Dialog):
    currKey: str
    panel: wx.Panel
    label: wx.StaticText
    modifierRadio: wx.RadioBox
    specialKeyCombo: wx.Choice
    keyEntry: wx.TextCtrl
    def __init__(self, parent, id, title, key: str) -> None: ...
    def updateUI(self) -> None: ...
    def onChangeModifier(self, evt) -> None: ...
    def onChangeSpecialKey(self, evt) -> None: ...
    def onApply(self, evt) -> None: ...

class HotKeyPanel(ScrolledPanel):
    parent = ...
    def __init__(self, parent) -> None: ...
    def updateUI(self) -> None: ...
    def onEdit(self, evt, key: str) -> None: ...

class HotKeyUI(wx.Dialog):
    parent = ...
    def __init__(self, parent, id, title) -> None: ...
