from abc import ABCMeta, abstractmethod

class LevelLoaderBase(metaclass=ABCMeta):
    defaultPath: str | None
    def __init__(self) -> None: ...
    @abstractmethod
    def initLoader(self) -> None: ...
    def cleanUp(self) -> None: ...
    def loadFromFile(self, fileName: str, filePath: str | None = None): ...
