from typing_extensions import Final, Literal

OBJ_UID: Final[Literal[0]]
OBJ_NP: Final[Literal[1]]
OBJ_DEF: Final[Literal[2]]
OBJ_MODEL: Final[Literal[3]]
OBJ_ANIM: Final[Literal[4]]
OBJ_PROP: Final[Literal[5]]
OBJ_RGBA: Final[Literal[6]]

PROP_UI_ENTRY: Final[str]
PROP_UI_COMBO: Final[str]
PROP_UI_RADIO: Final[str]
PROP_UI_CHECK: Final[str]
PROP_UI_SLIDE: Final[str]
PROP_UI_SPIN: Final[str]
PROP_UI_BLIND: Final[str]
PROP_UI_COMBO_DYNAMIC: Final[str]
PROP_UI_TIME: Final[str]

PROP_TYPE: Final[Literal[0]]
PROP_DATATYPE: Final[Literal[1]]
PROP_FUNC: Final[Literal[2]]
PROP_DEFAULT: Final[Literal[3]]
PROP_RANGE: Final[Literal[4]]
PROP_DYNAMIC_KEY: Final[Literal[5]]

PROP_MODEL: Final[str]

RANGE_MIN: Final[Literal[0]]
RANGE_MAX: Final[Literal[1]]
RANGE_RATE: Final[Literal[2]]
FUNC_NAME: Final[Literal[0]]
FUNC_ARGS: Final[Literal[1]]
PROP_INT: Final[Literal[0]]
PROP_BOOL: Final[Literal[1]]
PROP_FLOAT: Final[Literal[2]]
PROP_STR: Final[Literal[3]]
PROP_BLIND: Final[Literal[4]]

TYPE_CONV: Final[dict[Literal[0, 1, 2, 3], type]]

ARG_NAME: Final[str]
ARG_VAL: Final[str]
ARG_OBJ: Final[str]
ARG_NOLOADING: Final[str]
ARG_PARENT: Final[str]
