from collections.abc import Callable, Iterable
from typing import Any
from typing_extensions import TypeAlias

from ..wxwidgets.WxSlider import WxSlider

wx: Any
CubeColourDialog: TypeAlias = wx.lib.agw.cubecolourdialog.CubeColourDialog
PyEmbeddedImage: TypeAlias = wx.lib.embeddedimage.PyEmbeddedImage
ScrolledPanel: TypeAlias = wx.lib.scrolledpanel.ScrolledPanel

_Unused: TypeAlias = object

Key: PyEmbeddedImage

class AnimFileDrop(wx.FileDropTarget):
    editor = ...
    def __init__(self, editor) -> None: ...
    def OnDropFiles(self, x: _Unused, y: _Unused, filenames: Iterable[str]) -> None: ...

class ObjectPropUI(wx.Panel):
    parent = ...
    labelPane: wx.Panel
    label: wx.StaticText
    labelSizer: wx.BoxSizer
    setKeyButton: wx.BitmapButton
    uiPane: wx.Panel
    def __init__(self, parent, label) -> None: ...
    def onKey(self, evt) -> None: ...
    def setValue(self, value) -> None: ...
    def getValue(self): ...
    def bindFunc(self, inFunc, outFunc, valFunc=None) -> None: ...

class ObjectPropUIEntry(ObjectPropUI):
    ui: wx.TextCtrl
    eventType = ...
    def __init__(self, parent, label) -> None: ...
    def setValue(self, value: object) -> None: ...

class ObjectPropUISlider(ObjectPropUI):
    ui: WxSlider
    def __init__(self, parent, label, value, minValue: float, maxValue: float) -> None: ...

class ObjectPropUISpinner(ObjectPropUI):
    ui: wx.SpinCtrl
    eventType = ...
    def __init__(self, parent, label, value, minValue, maxValue) -> None: ...

class ObjectPropUICheck(ObjectPropUI):
    ui: wx.CheckBox
    eventType = ...
    def __init__(self, parent, label, value) -> None: ...

class ObjectPropUIRadio(ObjectPropUI):
    ui: wx.RadioBox
    eventType = ...
    def __init__(self, parent, label, value, valueList) -> None: ...
    def setValue(self, value) -> None: ...
    def getValue(self): ...

class ObjectPropUICombo(ObjectPropUI):
    ui: wx.Choice
    eventType = ...
    def __init__(self, parent, label, value, valueList, obj=None, callBack: Callable | None = None) -> None: ...
    def setItems(self, valueList) -> None: ...

class ObjectPropUITime(wx.Panel):
    parent = ...
    labelPane: wx.Panel
    label: wx.StaticText
    labelSizer: wx.BoxSizer
    uiPane: wx.Panel
    uiAmPm: wx.Choice
    uiHour: wx.Choice
    uiMin: wx.Choice
    eventType = ...
    def __init__(self, parent, label, value) -> None: ...
    def setValue(self, value: float) -> None: ...
    def getValue(self) -> float: ...
    def bindFunc(self, inFunc, outFunc, valFunc=None) -> None: ...

class ColorPicker(CubeColourDialog):
    updateCB = ...
    def __init__(self, parent, colourData=None, style=..., alpha: int = 255, updateCB=None, exitCB=None) -> None: ...
    def SetPanelColours(self) -> None: ...

class ObjectPropertyUI(ScrolledPanel):
    editor = ...
    colorPicker: ColorPicker | None
    lastColorPickerPos = ...
    lastPropTab = ...
    propPane: wx.Panel
    nb: wx.Notebook
    transformPane: wx.Panel
    propX: ObjectPropUIEntry
    propY: ObjectPropUIEntry
    propZ: ObjectPropUIEntry
    propH: ObjectPropUISlider
    propP: ObjectPropUISlider
    propR: ObjectPropUISlider
    propSX: ObjectPropUIEntry
    propSY: ObjectPropUIEntry
    propSZ: ObjectPropUIEntry
    lookPane: wx.Panel
    propCR: ObjectPropUISlider
    propCG: ObjectPropUISlider
    propCB: ObjectPropUISlider
    propCA: ObjectPropUISlider
    propsPane: wx.Panel
    def __init__(self, parent, editor) -> None: ...
    def clearPropUI(self) -> None: ...
    def colorPickerExitCB(self, evt=None) -> None: ...
    def colorPickerUpdateCB(self, rr: float, gg: float, bb: float, aa: float) -> None: ...
    def onColorSlider(self, evt) -> None: ...
    def openColorPicker(self, evt, colourData, alpha: int) -> None: ...
    def updateProps(self, obj, movable: bool = True) -> None: ...
