from typing import Any

import wx  # type: ignore[import]
from .PaletteTreeCtrl import PaletteTreeCtrl

class ObjectPaletteUI(wx.Panel):
    editor = ...
    palette: Any
    tree: PaletteTreeCtrl
    opSortAlpha: str
    opSortOrig: str
    opSort: str
    menuItems: list[str]
    popupmenu: wx.Menu
    def __init__(self, parent, editor) -> None: ...
    def populate(self) -> None: ...
    def onSelected(self, event) -> None: ...
    def onShowPopup(self, event) -> None: ...
    def onPopupItemSelected(self, event) -> None: ...
    def compareItems(self, item1, item2): ...
    def getSelected(self): ...
