from typing_extensions import SupportsIndex

from direct._typing import Obj
from direct.actor.Actor import Actor
from panda3d.core import NodePath

from .LevelEditor import LevelEditor

class ObjectHandler:
    editor: LevelEditor
    def __init__(self, editor: LevelEditor) -> None: ...
    def createDoubleSmiley(self, horizontal: bool = ...) -> NodePath: ...
    def updateDoubleSmiley(self, val: float, obj: Obj) -> None: ...
    def updateSmiley(self, val: SupportsIndex, obj: Obj) -> None: ...
    def createPanda(self) -> PandaActor: ...
    def createGrass(self) -> NodePath: ...

class PandaActor(Actor):
    def __init__(self) -> None: ...
