from .ObjectPaletteBase import ObjectBase, ObjectPaletteBase

class ObjectProp(ObjectBase): ...
class ObjectSmiley(ObjectProp): ...
class ObjectDoubleSmileys(ObjectProp): ...

class ObjectPalette(ObjectPaletteBase):
    def __init__(self) -> None: ...
