import wx  # type: ignore[import]

class PaletteTreeCtrl(wx.TreeCtrl):
    rootName: str
    root = ...
    paletteUI = ...
    opSortAlpha: str
    opSortOrig: str
    opSort: str
    def __init__(self, parent, treeStyle, rootName: str) -> None: ...
    def OnCompareItems(self, item1, item2): ...
    def SortTreeNodes(self, parent) -> None: ...
    def addTreeNodes(self, parentItem, parentItemName, items, itemKeys) -> None: ...
    def traverse(self, parent, itemText): ...
    def AddGroup(self) -> None: ...
    def DeleteItem(self, item) -> None: ...
    def DeleteSelected(self) -> None: ...
    def ReParent(self, parent, newParent) -> None: ...
    def ChangeHierarchy(self, itemName: str, x, y) -> None: ...
    def onBeginDrag(self, event) -> None: ...
