from collections.abc import Mapping, MutableSet

import wx  # type: ignore[import]
from .ObjectPaletteUI import ObjectPaletteUI
from .ProtoPaletteUI import ProtoPaletteUI

class PaletteTreeCtrl(wx.TreeCtrl):
    rootName: str
    root: wx.TreeItemId
    paletteUI: ObjectPaletteUI | ProtoPaletteUI
    opSortAlpha: str
    opSortOrig: str
    opSort: str
    def __init__(self, parent: ObjectPaletteUI | ProtoPaletteUI, treeStyle, rootName: str) -> None: ...
    def OnCompareItems(self, item1, item2): ...
    def SortTreeNodes(self, parent) -> None: ...
    def addTreeNodes(self, parentItem, parentItemName: str, items: Mapping[str, str], itemKeys: MutableSet[str]) -> None: ...
    def traverse(self, parent, itemText: str): ...
    def AddGroup(self) -> None: ...
    def DeleteItem(self, item) -> None: ...
    def DeleteSelected(self) -> None: ...
    def ReParent(self, parent, newParent) -> None: ...
    def ChangeHierarchy(self, itemName: str, x, y) -> None: ...
    def onBeginDrag(self, event) -> None: ...
