from _typeshed import SupportsWrite

class ProtoObjs:
    dirname: str
    name: str
    filename: str
    data: dict
    def __init__(self, name: str) -> None: ...
    def populate(self) -> None: ...
    def saveProtoData(self, f: SupportsWrite[str] | None) -> None: ...
    def saveToFile(self) -> None: ...
