from collections.abc import Sequence

import wx  # type: ignore[import]
from .PaletteTreeCtrl import PaletteTreeCtrl

class UniversalDropTarget(wx.PyDropTarget):
    editor = ...
    do: wx.DataObjectComposite
    filedo: wx.FileDataObject
    textdo: wx.TextDataObject
    bmpdo: wx.BitmapDataObject
    def __init__(self, editor) -> None: ...
    def OnData(self, x, y, d): ...

class ProtoPaletteUI(wx.Panel):
    editor = ...
    palette = ...
    tree: PaletteTreeCtrl
    editorTxt: str
    opSortAlpha: str
    opSortOrig: str
    opSort: str
    opAdd: str
    opDelete: str
    menuItemsGen: list[str]
    menuItemsSel: list[str]
    popupmenu: wx.Menu
    def __init__(self, parent, editor) -> None: ...
    def populate(self) -> None: ...
    def OnBeginLabelEdit(self, event) -> None: ...
    def OnEndLabelEdit(self, event) -> None: ...
    def menuAppendGenItems(self) -> None: ...
    def menuAppendSelItems(self) -> None: ...
    def onShowPopup(self, event) -> None: ...
    def onPopupItemSelected(self, event) -> None: ...
    def AquireFile(self, filename: str) -> None: ...
    def addNewItem(self, result: Sequence) -> None: ...
    def compareItems(self, item1, item2): ...
