from typing import TypeVar
from typing_extensions import Protocol

from .ObjectPaletteBase import ObjectPaletteBase

_T_contra = TypeVar('_T_contra', contravariant=True)

class _SupportsWrite(Protocol[_T_contra]):
    def write(self, s: _T_contra, /) -> object: ...

class ProtoPaletteBase(ObjectPaletteBase):
    def __init__(self) -> None: ...
    def addItems(self) -> None: ...
    def saveProtoDataStruct(self, f: _SupportsWrite[str] | None) -> None: ...
    def saveProtoData(self, f: _SupportsWrite[str] | None) -> None: ...
    def saveToFile(self) -> None: ...
