from _typeshed import SupportsWrite

from .ObjectPaletteBase import ObjectPaletteBase

class ProtoPaletteBase(ObjectPaletteBase):
    def __init__(self) -> None: ...
    def addItems(self) -> None: ...
    def saveProtoDataStruct(self, f: SupportsWrite[str] | None) -> None: ...
    def saveProtoData(self, f: SupportsWrite[str] | None) -> None: ...
    def saveToFile(self) -> None: ...
