__all__ = ['glob', 'iglob']

from typing import AnyStr, Generator

def glob(pathname: AnyStr) -> list[AnyStr]: ...
def iglob(pathname: AnyStr) -> Generator[AnyStr, None, None]: ...
def glob1(dirname: str | None, pattern: str) -> list[str]: ...
def glob0(dirname: str, basename: str) -> list[str]: ...
def has_magic(s: bytes | str) -> bool: ...
def escape(pathname: bytes | str) -> bytes: ...
