__all__ = ['glob', 'iglob']

from typing import AnyStr, Generator

def glob(pathname: AnyStr) -> list[AnyStr]: ...
def iglob(pathname: AnyStr) -> Generator[AnyStr, None, None]: ...
def glob1(dirname, pattern): ...
def glob0(dirname, basename: AnyStr) -> list[AnyStr]: ...
def has_magic(s: bytes | str) -> bool: ...
def escape(pathname: bytes | str) -> bytes: ...
