__all__ = ['StateData']

from typing import ClassVar
from typing_extensions import Literal, TypeAlias

from ..directnotify.Notifier import Notifier
from ..showbase.DirectObject import  DirectObject

_OldBool: TypeAlias = Literal[0, 1]

class StateData(DirectObject):
    notify: ClassVar[Notifier]
    doneEvent = ...
    doneStatus = ...
    isLoaded: bool | _OldBool
    isEntered: bool | _OldBool
    def __init__(self, doneEvent) -> None: ...
    def enter(self) -> _OldBool: ...
    def exit(self) -> _OldBool: ...
    def load(self) -> _OldBool: ...
    def unload(self) -> _OldBool: ...
    def getDoneStatus(self): ...
