from typing import ClassVar

from ..directnotify.Notifier import Notifier

class TaskTracker:
    notify: ClassVar[Notifier]
    MinSamples = ...
    SpikeThreshold = ...
    def __init__(self, namePrefix) -> None: ...
    def destroy(self) -> None: ...
    def flush(self) -> None: ...
    def getNamePrefix(self, namePrefix: object): ...
    def addProfileSession(self, session) -> None: ...
    def getAvgDuration(self): ...
    def getNumDurationSamples(self) -> int: ...
    def getAvgSession(self): ...
    def log(self) -> None: ...

class TaskProfiler:
    notify: ClassVar[Notifier]
    def __init__(self) -> None: ...
    def destroy(self) -> None: ...
    @staticmethod
    def GetDefaultSpikeThreshold() -> float: ...
    @staticmethod
    def SetSpikeThreshold(spikeThreshold) -> None: ...
    @staticmethod
    def GetSpikeThreshold(): ...
    def logProfiles(self, name=None) -> None: ...
    def flush(self) -> None: ...
