from typing import Any, ClassVar, overload
from panda3d.core import TypeHandle, TypedObject

class BasicSkel:
    DtoolClassDict: ClassVar[dict[str, Any]]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, __param0: BasicSkel) -> None: ...
    def set_value(self, n: int) -> None: ...
    def get_value(self) -> int: ...
    def set_value_alt(self, n: int) -> None: ...
    def get_value_alt(self) -> int: ...
    setValue = set_value
    getValue = get_value
    setValueAlt = set_value_alt
    getValueAlt = get_value_alt

class TypedSkel(TypedObject):
    DtoolClassDict: ClassVar[dict[str, Any]]
    def __init__(self) -> None: ...
    def set_value(self, n: int) -> None: ...
    def get_value(self) -> int: ...
    def set_value_alt(self, n: int) -> None: ...
    def get_value_alt(self) -> int: ...
    @staticmethod
    def get_class_type() -> TypeHandle: ...
    setValue = set_value
    getValue = get_value
    setValueAlt = set_value_alt
    getValueAlt = get_value_alt
    getClassType = get_class_type
