__all__ = ['EntryScale', 'EntryScaleGroup']

from collections.abc import Callable
from typing import Any

from panda3d.core import NodePath

Pmw: Any

class EntryScale(Pmw.MegaWidget):
    value = ...
    entryFormat: str
    fScaleCommand: bool
    labelFrame = ...
    entryValue = ...
    entry = ...
    label = ...
    minMaxFrame = ...
    minLabel = ...
    scale = ...
    maxLabel = ...
    def __init__(self, parent=None, **kw) -> None: ...
    def askForLabel(self, event=None) -> None: ...
    def askForMin(self, event=None) -> None: ...
    def setMin(self, newMin) -> None: ...
    def askForMax(self, event=None) -> None: ...
    def setMax(self, newMax) -> None: ...
    def askForResolution(self, event=None) -> None: ...
    def setResolution(self, newResolution) -> None: ...
    def get(self): ...
    def set(self, newVal, fCommand: bool = True) -> None: ...
    def onReturn(self, *args) -> None: ...
    def onReturnRelease(self, *args) -> None: ...
    def onPress(self, *args) -> None: ...
    def onRelease(self, *args) -> None: ...

class EntryScaleGroup(Pmw.MegaToplevel):
    balloon = ...
    toggleBalloonVar = ...
    entryScaleList: list
    def __init__(self, parent=None, **kw): ...
    def toggleBalloon(self) -> None: ...
    def get(self): ...
    def getAt(self, index: int): ...
    def set(self, value, fCommand: bool = True) -> None: ...
    def setAt(self, index: int, value) -> None: ...
    def reset(self) -> None: ...
    def onReturn(self, *args) -> None: ...
    def onReturnRelease(self, *args) -> None: ...
    def onPress(self, *args) -> None: ...
    def onRelease(self, *args) -> None: ...

def rgbPanel(nodePath: NodePath, callback: Callable[[Any], object] | None = None) -> EntryScaleGroup: ...
