__all__ = ['ColorEntry', 'VectorEntry', 'Vector2Entry', 'Vector3Entry', 'Vector4Entry']

from tkinter import Menu, Menubutton
from typing import Any

from .Valuator import ValuatorGroupPanel

Pmw: Any

class VectorEntry(Pmw.MegaWidget):
    entryFormat: str
    menu: Menu
    variableList: list
    entryList: list
    entryBackground = ...
    def __init__(self, parent=None, **kw): ...
    def menu(self) -> Menu: ...
    def label(self) -> Menubutton: ...
    def entry(self, index: int) -> Pmw.EntryField: ...
    def entryList(self) -> list[Pmw.EntryField]: ...
    def floaters(self) -> ValuatorGroupPanel: ...
    def get(self): ...
    def getAt(self, index: int): ...
    def set(self, value, fCommand: bool = True) -> None: ...
    def setAt(self, index: int, value, fCommand: bool = True) -> None: ...
    def action(self, fCommand: bool = True) -> None: ...
    def reset(self) -> None: ...
    def addMenuItem(self, label: str = '', command=None) -> None: ...
    def popupSliders(self) -> None: ...

class Vector2Entry(VectorEntry): ...
class Vector3Entry(VectorEntry): ...
class Vector4Entry(VectorEntry): ...

class ColorEntry(VectorEntry):
    def popupColorPicker(self) -> None: ...
