class Logger:
    def __init__(self, fileName: str = 'log') -> None: ...
    def setTimeStamp(self, bool: bool) -> None: ...
    def getTimeStamp(self) -> bool: ...
    def resetStartTime(self) -> None: ...
    def log(self, entryString: str) -> None: ...
