from typing import Any, ClassVar
from panda3d.core import ClientBase, TypeHandle, ostream

class VrpnClient(ClientBase):
    """A specific ClientBase that connects to a VRPN server and records
    information on the connected VRPN devices.
    """
    DtoolClassDict: ClassVar[dict[str, Any]]
    def __init__(self, server_name: str) -> None: ...
    def get_server_name(self) -> str: ...
    def is_valid(self) -> bool: ...
    def is_connected(self) -> bool: ...
    def write(self, out: ostream, indent_level: int = ...) -> None: ...
    @staticmethod
    def get_class_type() -> TypeHandle: ...
    getServerName = get_server_name
    isValid = is_valid
    isConnected = is_connected
    getClassType = get_class_type
