def throw_new_frame() -> None: ...
def init_app_for_gui() -> None: ...
def store_accessibility_shortcut_keys() -> None:
    """to handle windows stickykeys"""
def allow_accessibility_shortcut_keys(allowKeys: bool, /) -> None: ...
throwNewFrame = throw_new_frame
initAppForGui = init_app_for_gui
storeAccessibilityShortcutKeys = store_accessibility_shortcut_keys
allowAccessibilityShortcutKeys = allow_accessibility_shortcut_keys
