__all__ = ['DirectEntry']

from _typeshed import Unused
from collections.abc import Callable, Collection, Iterable
from typing import Any, ClassVar, Final, Unpack

from panda3d.core import AudioSound, ConfigVariableBool, NodePath, PGEntry, TextFont

from ._typing import FrameKeywords
from .DirectFrame import DirectFrame
from .OnscreenText import OnscreenText

ENTRY_FOCUS_STATE: Final = 0
ENTRY_NO_FOCUS_STATE: Final = 1
ENTRY_INACTIVE_STATE: Final = 2

class DirectEntry(DirectFrame[PGEntry]):
    directWtext: ClassVar[ConfigVariableBool]
    AllowCapNamePrefixes: ClassVar[tuple[str, ...]]
    ForceCapNamePrefixes: ClassVar[tuple[str, ...]]
    onscreenText: OnscreenText
    unicodeText: bool
    def __init__(
        self,
        parent: NodePath | None = None,
        *,
        pgFunc: Callable[[str], PGEntry] = ...,
        entryFont: TextFont | None = None,
        width: float = 10,
        numLines: int = 1,
        focus: bool = False,
        cursorKeys: bool = True,
        obscured: bool = False,
        backgroundFocus: bool = False,
        initialText: str = '',
        overflow: bool = False,
        command: Callable[..., object] | None = None,
        extraArgs: list[Any] = ...,
        failedCommand: Callable[..., object] | None = None,
        failedExtraArgs: list[Any] = ...,
        focusInCommand: Callable[..., object] | None = None,
        focusInExtraArgs: Iterable[Any] = ...,
        focusOutCommand: Callable[..., object] | None = None,
        focusOutExtraArgs: Iterable[Any] = ...,
        rolloverSound: AudioSound | None = ...,
        clickSound: AudioSound | None = ...,
        autoCapitalize: bool = False,
        autoCapitalizeAllowPrefixes: Collection[str] = ...,
        autoCapitalizeForcePrefixes: Collection[str] = ...,
        **kw: Unpack[FrameKeywords],
    ) -> None: ...
    def setup(self) -> None: ...
    def updateWidth(self) -> None: ...
    def updateNumLines(self) -> None: ...
    def setFocus(self) -> None: ...
    def setCursorKeysActive(self) -> None: ...
    def setOverflowMode(self) -> None: ...
    def setObscureMode(self) -> None: ...
    def setBackgroundFocus(self) -> None: ...
    def setRolloverSound(self) -> None: ...
    def setClickSound(self) -> None: ...
    def commandFunc(self, event: Unused) -> None: ...
    def failedCommandFunc(self, event: Unused) -> None: ...
    def autoCapitalizeFunc(self) -> None: ...
    def focusInCommandFunc(self) -> None: ...
    def focusOutCommandFunc(self) -> None: ...
    def set(self, text: str) -> None: ...
    def get(self, plain: bool = False) -> str: ...
    def getCursorPosition(self) -> int: ...
    def setCursorPosition(self, pos: int) -> None: ...
    def getNumCharacters(self) -> int: ...
    def enterText(self, text: str) -> None: ...
    def getFont(self) -> TextFont: ...
    def getBounds(self, state: Unused = 0) -> tuple[float, float, float, float]: ...  # type: ignore[override]
