__all__ = ['DirectScrolledFrame']

from typing import Any

from panda3d.core import NodePath

from .DirectFrame import DirectFrame
from .DirectScrollBar import DirectScrollBar

class DirectScrolledFrame(DirectFrame):
    verticalScroll: DirectScrollBar
    horizontalScroll: DirectScrollBar
    canvas: NodePath
    def __init__(self, parent: NodePath | None = None, **kw: Any) -> None: ...
    def setScrollBarWidth(self) -> None: ...
    def setCanvasSize(self) -> None: ...
    def getCanvas(self) -> NodePath: ...
    def setManageScrollBars(self) -> None: ...
    def setAutoHideScrollBars(self) -> None: ...
    def commandFunc(self) -> None: ...
