__all__ = ['DirectWaitBar']

from typing import Any

from panda3d.core import NodePath, PGFrameStyle
from .DirectFrame import DirectFrame

class DirectWaitBar(DirectFrame):
    barStyle: PGFrameStyle
    def __init__(self, parent: NodePath | None = None, **kw: Any) -> None: ...
    def setRange(self) -> None: ...
    def setValue(self) -> None: ...
    def getPercent(self) -> float: ...
    def updateBarStyle(self) -> None: ...
    def setBarRelief(self) -> None: ...
    def setBarBorderWidth(self) -> None: ...
    def setBarColor(self) -> None: ...
    def setBarTexture(self) -> None: ...
    def update(self, value) -> None: ...
    def finish(self, N: float = 10) -> None: ...
