__all__ = ['DirectScrollBar']

from typing import Any

from panda3d.core import NodePath
from .DirectButton import DirectButton
from .DirectFrame import DirectFrame

class DirectScrollBar(DirectFrame):
    thumb: DirectButton
    incButton: DirectButton
    decButton: DirectButton
    def __init__(self, parent: NodePath | None = ..., **kw: Any) -> None: ...
    def setRange(self) -> None: ...
    def setValue(self, value: float) -> None: ...
    def getValue(self) -> float: ...
    def getRatio(self) -> float: ...
    def setScrollSize(self) -> None: ...
    def setPageSize(self) -> None: ...
    def scrollStep(self, stepCount: int) -> None: ...
    def scrollPage(self, pageCount: int) -> None: ...
    def setOrientation(self) -> None: ...
    def setManageButtons(self) -> None: ...
    def setResizeThumb(self) -> None: ...
    def commandFunc(self) -> None: ...
