__all__ = ['DirectRadioButton']

from collections.abc import Iterable
from typing import Any

from panda3d.core import NodePath
from .DirectButton import DirectButton
from .DirectLabel import DirectLabel

class DirectRadioButton(DirectButton):
    colors = ...
    indicator: DirectLabel
    def __init__(self, parent: NodePath | None = None, **kw: Any) -> None: ...
    def resetFrameSize(self) -> None: ...
    def setFrameSize(self, fClearFrame: bool = False) -> None: ...
    def commandFunc(self, event: object) -> None: ...
    def check(self) -> None: ...
    def setOthers(self, others: Iterable[DirectRadioButton]) -> None: ...
    def uncheck(self) -> None: ...
    def setIndicatorValue(self) -> None: ...
