__all__ = ['DirectButton']

from typing import Any
from typing_extensions import TypeAlias

from panda3d.core import NodePath
from .DirectFrame import DirectFrame

_Unused: TypeAlias = object

class DirectButton(DirectFrame):
    def __init__(self, parent: NodePath | None = None, **kw: Any) -> None: ...
    def setCommandButtons(self) -> None: ...
    def commandFunc(self, event: _Unused) -> None: ...
    def setClickSound(self) -> None: ...
    def setRolloverSound(self) -> None: ...
