__all__ = ['DirectFrame']

from collections.abc import Sequence
from typing import Any, ClassVar
from typing_extensions import Literal, TypeAlias

from panda3d.core import NodePath, Texture
from .DirectGuiBase import DirectGuiWidget

_Geom: TypeAlias = NodePath | str
_Image: TypeAlias = NodePath | Texture | tuple[str, str] | str

class DirectFrame(DirectGuiWidget):
    DefDynGroups: ClassVar[tuple[Literal['text'], Literal['geom'], Literal['image']]]
    def __init__(self, parent: NodePath | None = None, **kw: Any) -> None: ...
    def clearText(self) -> None: ...
    def setText(self, text: str | Sequence[str] | None = None) -> None: ...
    def clearGeom(self) -> None: ...
    def setGeom(self, geom: _Geom | Sequence[_Geom | None] | None = None) -> None: ...
    def clearImage(self) -> None: ...
    def setImage(self, image: _Image | Sequence[_Image | None] | None = None) -> None: ...
