from panda3d.physics import BaseForce
from .ForceGroup import ForceGroup

class GlobalForceGroup(ForceGroup):
    def __init__(self, name: str | None = None) -> None: ...
    def addForce(self, force: BaseForce) -> None: ...
    def removeForce(self, force: BaseForce) -> None: ...
