from os import PathLike
from typing_extensions import TypeAlias

from panda3d.core import ConfigVariableFilename, Filename
from panda3d.physics import SpriteParticleRenderer

_Filename: TypeAlias = Filename | ConfigVariableFilename | str | bytes | PathLike

class SpriteParticleRendererExt(SpriteParticleRenderer):
    sourceTextureName: str
    sourceFileName: str
    sourceNodeName: str
    def getSourceTextureName(self) -> str: ...
    def setSourceTextureName(self, name: str) -> None: ...
    def setTextureFromFile(self, fileName: _Filename | None = None) -> bool: ...
    def addTextureFromFile(self, fileName: _Filename | None = None) -> bool: ...
    def getSourceFileName(self) -> str: ...
    def setSourceFileName(self, name: str) -> None: ...
    def getSourceNodeNamee(self) -> str: ...
    def setSourceNodeName(self, name: str) -> None: ...
    def setTextureFromNode(self, modelName: str | None = None, nodeName: str | None = None, sizeFromTexels: bool = False) -> bool: ...
    def addTextureFromNode(self, modelName: str | None = None, nodeName: str | None = None, sizeFromTexels: bool = False) -> bool: ...
