from _typeshed import StrOrBytesPath

from panda3d.physics import SpriteParticleRenderer

class SpriteParticleRendererExt(SpriteParticleRenderer):
    sourceTextureName: str | None
    sourceFileName: str | None
    sourceNodeName: str | None
    def getSourceTextureName(self) -> str: ...
    def setSourceTextureName(self, name: str) -> None: ...
    def setTextureFromFile(self, fileName: StrOrBytesPath | None = ...) -> bool: ...
    def addTextureFromFile(self, fileName: StrOrBytesPath | None = ...) -> bool: ...
    def getSourceFileName(self) -> str: ...
    def setSourceFileName(self, name: str) -> None: ...
    def getSourceNodeName(self) -> str: ...
    def setSourceNodeName(self, name: str) -> None: ...
    def setTextureFromNode(self, modelName: str | None = ..., nodeName: str | None = ..., sizeFromTexels: bool = ...) -> bool: ...
    def addTextureFromNode(self, modelName: str | None = ..., nodeName: str | None = ..., sizeFromTexels: bool = ...) -> bool: ...
