from collections.abc import Sequence
from typing import SupportsInt, SupportsRound

from direct._typing import AnyReal
from panda3d.core import Filename, NodePath

def ROUND_TO(value: float, divisor: AnyReal) -> AnyReal: ...
def ROUND_INT(val: SupportsRound[SupportsInt]) -> int: ...
def CLAMP(val: AnyReal, minVal: AnyReal, maxVal: AnyReal) -> AnyReal: ...
def getTkColorString(color: Sequence[SupportsInt]) -> str: ...
def lerpBackgroundColor(r: float, g: float, b: float, duration: float) -> None: ...
def useDirectRenderStyle(nodePath: NodePath, priority: int = ...) -> None: ...
def getFileData(filename: Filename, separator: str | None = ...) -> list[list[str]]: ...
