from collections.abc import Sequence
from typing import SupportsInt, SupportsRound, TypeVar

from panda3d.core import Filename, NodePath

_AnyReal = TypeVar('_AnyReal', int, float)

def ROUND_TO(value: float, divisor: _AnyReal) -> _AnyReal: ...
def ROUND_INT(val: SupportsRound[SupportsInt]) -> int: ...
def CLAMP(val: _AnyReal, minVal: _AnyReal, maxVal: _AnyReal) -> _AnyReal: ...
def getTkColorString(color: Sequence[SupportsInt]) -> str: ...
def lerpBackgroundColor(r: float, g: float, b: float, duration) -> None: ...
def useDirectRenderStyle(nodePath: NodePath, priority: int = 0) -> None: ...
def getFileData(filename: Filename, separator: str | None = ',') -> list[list[str]]: ...
