__all__ = ['CRDataCache']

from .CachedDOData import CachedDOData

class CRDataCache:
    def __init__(self) -> None: ...
    def destroy(self) -> None: ...
    def setCachedData(self, doId: int, name: str, data: CachedDOData) -> None: ...
    def hasCachedData(self, doId: int) -> bool: ...
    def popCachedData(self, doId: int) -> CachedDOData: ...
    def flush(self) -> None: ...
