from typing import ClassVar
from typing_extensions import Literal

from ..showbase.PythonUtil import Enum

class DummyTaskClass:
    def setDelay(self, blah: object) -> None: ...

DummyTask: DummyTaskClass

class DistributedSmoothNodeBase:
    BoradcastTypes: ClassVar[Enum]
    def __init__(self) -> None: ...
    def generate(self) -> None: ...
    def disable(self) -> None: ...
    def delete(self) -> None: ...
    def b_clearSmoothing(self) -> None: ...
    def d_clearSmoothing(self) -> None: ...
    def getPosHprBroadcastTaskName(self) -> str: ...
    def setPosHprBroadcastPeriod(self, period: float) -> None: ...
    def getPosHprBroadcastPeriod(self) -> float: ...
    def stopPosHprBroadcast(self) -> None: ...
    def posHprBroadcastStarted(self) -> bool: ...
    def wantSmoothPosBroadcastTask(self) -> Literal[True]: ...
    def startPosHprBroadcast(self, period: float = 0.2, stagger: bool = False, type=None) -> None: ...
    def sendCurrentPosition(self) -> None: ...
