from typing import Literal

from panda3d.core import NodePath

from .ClientRepository import ClientRepository
from .DistributedObjectAI import DistributedObjectAI
from .GridParent import GridParent

class DistributedNodeAI(DistributedObjectAI, NodePath):
    DistributedNodeAI_initialized: Literal[1]
    gridParent: GridParent | None
    def __init__(self, air: ClientRepository, name: str | None = None) -> None: ...
    def setLocation(self, parentId: int, zoneId: int, teleport: bool = ...) -> None: ...
    def b_setParent(self, parentToken: str | int) -> None: ...
    def d_setParent(self, parentToken: str | int) -> None: ...
    def setParentStr(self, parentToken: str) -> None: ...
    def setParent(self, parentToken: int) -> None: ...
    def do_setParent(self, parentToken: int) -> None: ...
    def d_setX(self, x: float) -> None: ...
    def d_setY(self, y: float) -> None: ...
    def d_setZ(self, z: float) -> None: ...
    def d_setH(self, h: float) -> None: ...
    def d_setP(self, p: float) -> None: ...
    def d_setR(self, r: float) -> None: ...
    def setXY(self, x: float, y: float) -> None: ...
    def d_setXY(self, x: float, y: float) -> None: ...
    def d_setPos(self, x: float, y: float, z: float) -> None: ...
    def d_setHpr(self, h: float, p: float, r: float) -> None: ...
    def setXYH(self, x: float, y: float, h: float) -> None: ...
    def d_setXYH(self, x: float, y: float, h: float) -> None: ...
    def b_setXYZH(self, x: float, y: float, z: float, h: float) -> None: ...
    def setXYZH(self, x: float, y: float, z: float, h: float) -> None: ...
    def getXYZH(self) -> tuple[float, float, float, float]: ...
    def d_setXYZH(self, x: float, y: float, z: float, h: float) -> None: ...
    def b_setPosHpr(self, x: float, y: float, z: float, h: float, p: float, r: float) -> None: ...
    def d_setPosHpr(self, x: float, y: float, z: float, h: float, p: float, r: float) -> None: ...
