from typing import ClassVar

from panda3d.direct import DCClass
from ..directnotify.Notifier import Notifier
from ..showbase.DirectObject import DirectObject
from .ClientRepository import ClientRepository

class DistributedObjectBase(DirectObject):
    notify: ClassVar[Notifier]
    cr: ClientRepository
    parentId: int | None
    zoneId: int | None
    doId: int
    dclass: DCClass
    def __init__(self, cr: ClientRepository) -> None: ...
    def getLocation(self) -> tuple[int | None, int | None] | None: ...
    def handleChildArrive(self, childObj, zoneId: int) -> None: ...
    def handleChildArriveZone(self, childObj, zoneId: int) -> None: ...
    def handleChildLeave(self, childObj, zoneId: int) -> None: ...
    def handleChildLeaveZone(self, childObj, zoneId: int) -> None: ...
    def handleQueryObjectChildrenLocalDone(self, context) -> None: ...
    def getParentObj(self) -> DistributedObjectBase | None: ...
    def hasParentingRules(self) -> bool: ...
    def delete(self) -> None: ...
