from _typeshed import Unused
from enum import IntEnum

class DummyTaskClass:
    def setDelay(self, blah: Unused) -> None: ...

DummyTask: DummyTaskClass

class DistributedSmoothNodeBase:
    class BroadcastTypes(IntEnum):
        FULL = 0
        XYH = 1
        XY = 2

    def __init__(self) -> None: ...
    def generate(self) -> None: ...
    def disable(self) -> None: ...
    def delete(self) -> None: ...
    def b_clearSmoothing(self) -> None: ...
    def d_clearSmoothing(self) -> None: ...
    def getPosHprBroadcastTaskName(self) -> str: ...
    def setPosHprBroadcastPeriod(self, period: float) -> None: ...
    def getPosHprBroadcastPeriod(self) -> float: ...
    def stopPosHprBroadcast(self) -> None: ...
    def posHprBroadcastStarted(self) -> bool: ...
    def wantSmoothPosBroadcastTask(self) -> bool: ...
    def startPosHprBroadcast(self, period: float = 0.2, stagger: bool = ..., type=None) -> None: ...
    def sendCurrentPosition(self) -> None: ...
