from collections.abc import Callable, Iterable, Sequence
from typing import Any, ClassVar
from typing_extensions import Literal, TypeAlias

from panda3d.core import DatagramIterator
from panda3d.direct import DCClass
from ..directnotify.Notifier import Notifier
from .ClientRepository import ClientRepository
from .DistributedObjectBase import DistributedObjectBase
from .DoInterestManager import InterestHandle

_State: TypeAlias = Literal[1, 2, 3, 4, 5, 6]

ESNew: Literal[1]
ESDeleted: Literal[2]
ESDisabling: Literal[3]
ESDisabled: Literal[4]
ESGenerating: Literal[5]
ESGenerated: Literal[6]
ESNum2Str: dict[_State, str]

class DistributedObject(DistributedObjectBase):
    notify: ClassVar[Notifier]
    neverDisable: bool
    DistributedObject_initialized: Literal[1]
    activeState: _State
    cacheable: bool
    def __init__(self, cr: ClientRepository) -> None: ...
    def getAutoInterests(self) -> list[int]: ...
    def setNeverDisable(self, bool: bool) -> None: ...
    def getNeverDisable(self) -> bool: ...
    def setCachedData(self, name: str, data) -> None: ...
    def hasCachedData(self, name: str) -> bool: ...
    def getCachedData(self, name: str): ...
    def flushCachedData(self, name: str) -> None: ...
    def setCacheable(self, bool: bool) -> None: ...
    def getCacheable(self) -> bool: ...
    def deleteOrDelay(self) -> None: ...
    def disableAnnounceAndDelete(self) -> None: ...
    def getDelayDeleteCount(self) -> int: ...
    def getDelayDeleteEvent(self) -> str: ...
    def getDisableEvent(self) -> str: ...
    def disableAndAnnounce(self) -> None: ...
    def announceGenerate(self) -> None: ...
    def disable(self) -> None: ...
    def isDisabled(self) -> bool: ...
    def isGenerated(self) -> bool: ...
    def delete(self) -> None: ...
    def generate(self) -> None: ...
    def generateInit(self) -> None: ...
    def getDoId(self) -> int: ...
    def postGenerateMessage(self) -> None: ...
    def updateRequiredFields(self, dclass: DCClass, di: DatagramIterator) -> None: ...
    def updateAllRequiredFields(self, dclass: DCClass, di: DatagramIterator) -> None: ...
    def updateRequiredOtherFields(self, dclass: DCClass, di: DatagramIterator) -> None: ...
    def sendUpdate(self, fieldName: str, args=..., sendToId: int | None = None) -> None: ...
    def sendDisableMsg(self) -> None: ...
    def sendDeleteMsg(self) -> None: ...
    def taskName(self, taskString: object) -> str: ...
    def uniqueName(self, idString: object) -> str: ...
    def getCallbackContext(self, callback: Callable[..., object], extraArgs: Sequence[Any] = ...) -> int: ...
    def getCurrentContexts(self) -> list[int]: ...
    def getCallback(self, context: int) -> Callable[..., object]: ...
    def getCallbackArgs(self, context: int) -> Sequence[Any]: ...
    def doCallbackContext(self, context: int, args: Sequence[Any]) -> None: ...
    def setBarrierData(self, data: Iterable) -> None: ...
    def getBarrierData(self) -> tuple[tuple[int, str, list]]: ...
    def doneBarrier(self, name: str | None = None) -> None: ...
    def addInterest(self, zoneId: int, note: str = '', event: str | None = None) -> InterestHandle | None: ...
    def removeInterest(self, handle: InterestHandle, event: str | None = None) -> bool: ...
    def b_setLocation(self, parentId: int, zoneId: int) -> None: ...
    def d_setLocation(self, parentId: int, zoneId: int) -> None: ...
    def setLocation(self, parentId: int | None, zoneId: int | None) -> None: ...
    def getLocation(self) -> tuple[int | None, int | None] | None: ...
    def getParentObj(self) -> DistributedObjectBase | None: ...
    def isLocal(self) -> bool: ...
    def isGridParent(self) -> bool: ...
    def execCommand(self, string, mwMgrId, avId, zoneId) -> None: ...
