from typing_extensions import Literal

from .ClientRepository import ClientRepository
from .DistributedObjectUD import DistributedObjectUD

class DistributedNodeUD(DistributedObjectUD):
    DistributedNodeUD_initialized: Literal[1]
    def __init__(self, air: ClientRepository, name: str | None = ...) -> None: ...
    def b_setParent(self, parentToken) -> None: ...
    def d_setParent(self, parentToken) -> None: ...
    def setParentStr(self, parentToken: str) -> None: ...
    def setParent(self, parentToken) -> None: ...
    def do_setParent(self, parentToken) -> None: ...
    def d_setX(self, x: float) -> None: ...
    def d_setY(self, y: float) -> None: ...
    def d_setZ(self, z: float) -> None: ...
    def d_setH(self, h: float) -> None: ...
    def d_setP(self, p: float) -> None: ...
    def d_setR(self, r: float) -> None: ...
    def setXY(self, x: float, y: float) -> None: ...
    def d_setXY(self, x: float, y: float) -> None: ...
    def d_setPos(self, x: float, y: float, z: float) -> None: ...
    def d_setHpr(self, h: float, p: float, r: float) -> None: ...
    def setXYH(self, x: float, y: float, h: float) -> None: ...
    def d_setXYH(self, x: float, y: float, h: float) -> None: ...
    def setXYZH(self, x: float, y: float, z: float, h: float) -> None: ...
    def d_setXYZH(self, x: float, y: float, z: float, h: float) -> None: ...
    def d_setPosHpr(self, x: float, y: float, z: float, h: float, p: float, r: float) -> None: ...
