from collections.abc import Callable
from typing import ClassVar

from direct.directnotify.Notifier import Notifier
from .DistributedObjectBase import DistributedObjectBase

class DoHierarchy:
    notify: ClassVar[Notifier]
    def __init__(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def __len__(self) -> int: ...
    def clear(self) -> None: ...
    def getDoIds(
        self, getDo: Callable[[int], object], parentId: int, zoneId: int | None = None, classType: type | None = None
    ) -> list[int]: ...
    def storeObjectLocation(self, do: DistributedObjectBase, parentId: int, zoneId: int) -> None: ...
    def deleteObjectLocation(self, do: DistributedObjectBase, parentId: int, zoneId: int) -> None: ...
