from .DistributedObject import DistributedObject

class GridChild:
    def __init__(self) -> None: ...
    def delete(self) -> None: ...
    def setGridCell(self, grid: DistributedObject, zoneId: int) -> None: ...
    def updateGridInterest(self, grid: DistributedObject, zoneId: int) -> None: ...
    def enableGridInterest(self, enabled: bool = True) -> None: ...
    def isOnAGrid(self) -> bool: ...
    def getGrid(self) -> None: ...
    def getGridZone(self) -> None: ...
    def getGridInterestIds(self) -> list[int]: ...
    def getGridInterestZoneId(self, gridDoId: int) -> int | None: ...

class SmoothGridChild(GridChild):
    def transformTelemetry(
        self, x: float, y: float, z: float, h: float, p: float, r: float, e: int
    ) -> tuple[float, float, float, float, float, float]: ...
