from typing import ClassVar

from direct._typing import Incomplete
from direct.directnotify.Notifier import Notifier
from panda3d.core import NodePath

class ParentMgr:
    notify: ClassVar[Notifier]
    token2nodepath: dict[Incomplete, NodePath]
    pendingParentToken2children: dict[Incomplete, list[NodePath]]
    pendingChild2parentToken: dict[NodePath, Incomplete]
    def __init__(self) -> None: ...
    def destroy(self) -> None: ...
    def privRemoveReparentRequest(self, child: NodePath) -> None: ...
    def requestReparent(self, child: NodePath, parentToken) -> None: ...
    def registerParent(self, token, parent: NodePath) -> None: ...
    def unregisterParent(self, token) -> None: ...
