from typing import Any, ClassVar

from direct.directnotify.Notifier import Notifier
from panda3d.core import NodePath

class ParentMgr:
    notify: ClassVar[Notifier]
    token2nodepath: dict[Any, NodePath]
    pendingParentToken2children: dict[Any, list[NodePath]]
    pendingChild2parentToken: dict[NodePath, Any]
    def __init__(self) -> None: ...
    def destroy(self) -> None: ...
    def privRemoveReparentRequest(self, child: NodePath) -> None: ...
    def requestReparent(self, child: NodePath, parentToken) -> None: ...
    def registerParent(self, token, parent: NodePath) -> None: ...
    def unregisterParent(self, token) -> None: ...
