from _typeshed import Incomplete
from typing import ClassVar

from direct.directnotify.Notifier import Notifier
from panda3d.core import NodePath

class ParentMgr:
    notify: ClassVar[Notifier]
    token2nodepath: dict[int | Incomplete, NodePath]
    pendingParentToken2children: dict[int | Incomplete, list[NodePath]]
    pendingChild2parentToken: dict[NodePath, int | Incomplete]
    def __init__(self) -> None: ...
    def destroy(self) -> None: ...
    def privRemoveReparentRequest(self, child: NodePath) -> None: ...
    def requestReparent(self, child: NodePath, parentToken: int | Incomplete) -> None: ...
    def registerParent(self, token: int | Incomplete, parent: NodePath) -> None: ...
    def unregisterParent(self, token: int | Incomplete) -> None: ...
