from collections.abc import Callable
from typing import Any, ClassVar, SupportsFloat

from panda3d.core import Datagram, DatagramIterator

class PyDatagramIterator(DatagramIterator):
    FuncDict: ClassVar[dict[int, Callable[[], Any]]]
    def getChannel(self) -> int: ...
    def __init__(self, datagram: Datagram | None = None, offset: int = 0) -> None: ...
    def assign(self, datagram: Datagram, offset: int = 0) -> None: ...
    def getArg(self, subatomicType: int, divisor: SupportsFloat = 1) -> list[Any]: ...
