from .ClientRepository import ClientRepository
from .DistributedObject import DistributedObject

class SampleObject(DistributedObject):
    def __init__(self, cr: ClientRepository) -> None: ...
    def setColor(self, red: int = 0, green: int = 0, blue: int = 0) -> None: ...
    def getColor(self) -> tuple[int, int, int]: ...
