from typing import ClassVar
from typing_extensions import Literal

class StagedObject:
    UNKNOWN: ClassVar[Literal[-1]]
    OFF: ClassVar[Literal[0]]
    ON: ClassVar[Literal[1]]
    def __init__(self, initState: Literal[-1, 0, 1] = ...) -> None: ...
    def goOnStage(self) -> None: ...
    def handleOnStage(self) -> None: ...
    def goOffStage(self) -> None: ...
    def handleOffStage(self) -> None: ...
    def isOnStage(self) -> bool: ...
    def isOffStage(self) -> bool: ...
