from typing import ClassVar
from typing_extensions import Literal

from .ClientRepository import ClientRepository
from .DistributedObject import DistributedObject

class TimeManager(DistributedObject):
    updateFreq: ClassVar[float]
    minWait: ClassVar[float]
    maxUncertainty: ClassVar[float]
    maxAttempts: ClassVar[int]
    extraSkew: ClassVar[int]
    reportFrameRateInterval: ClassVar[bool]
    thisContext: int
    nextContext: int
    attemptCount: int
    start: int
    lastAttempt: float
    def __init__(self, cr: ClientRepository) -> None: ...
    def generate(self) -> None: ...
    def announceGenerate(self) -> None: ...
    def disable(self) -> None: ...
    def delete(self) -> None: ...
    def startTask(self) -> None: ...
    def stopTask(self) -> None: ...
    def doUpdate(self, task: object) -> Literal[0]: ...
    def handleClockError(self) -> None: ...
    def synchronize(self, description: str) -> bool: ...
    def serverTime(self, context: int, timestamp: int) -> None: ...
